# =====================================================
# APPLICATION
# =====================================================

spring.application.name=APPOINTMENT-SERVICE

server.port=8083


# =====================================================
# POSTGRESQL
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/healthconnect

spring.datasource.username=postgres

spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver


# =====================================================
# JPA
# =====================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =====================================================
# EUREKA
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true