# =====================================================
# API GATEWAY
# =====================================================

spring.application.name=API-GATEWAY

server.port=8080


# =====================================================
# EUREKA SERVER
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


# =====================================================
# ROUTE 1 - PATIENT SERVICE
# =====================================================

spring.cloud.gateway.server.webflux.routes[0].id=PATIENT-SERVICE

spring.cloud.gateway.server.webflux.routes[0].uri=lb://PATIENT-SERVICE

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/ms1/**

spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker

spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=patientCB

spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback/patient


# =====================================================
# ROUTE 2 - APPOINTMENT SERVICE
# =====================================================

spring.cloud.gateway.server.webflux.routes[1].id=APPOINTMENT-SERVICE

spring.cloud.gateway.server.webflux.routes[1].uri=lb://APPOINTMENT-SERVICE

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/ms3/**

spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker

spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=appointmentCB

spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/appointment


# =====================================================
# CIRCUIT BREAKER
# =====================================================

resilience4j.timelimiter.configs.default.timeout-duration=5s

resilience4j.circuitbreaker.configs.default.sliding-window-size=3

resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50

resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=30s


# =====================================================
# CORS
# =====================================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true